NAME= 'Artem'
EMAIL = 'ArtemMyazov8000@yandex.ru'
PASSWORD = '123456'
SHORT_PASSWORD = '12345'
URL_MAIN_PAGE = 'https://stellarburgers.nomoreparties.site/'
URL_PERS_ACC_PAGE = 'https://stellarburgers.nomoreparties.site/account/profile'
URL_LOGIN_PAGE = 'https://stellarburgers.nomoreparties.site/login'